# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.TextField(help_text='max. 300 characters.', max_length=300, verbose_name='What problem or societal need are you working on?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='outcome',
            field=models.TextField(help_text='If your project is selected, what will be different a year from now? What will have changed? (max. 300 characters).', max_length=300, verbose_name='What would be a successful outcome for your project?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='plan',
            field=models.TextField(help_text='Describe as concretely as possible the approach and / or the method you will use when implementing your idea. What are the steps you plan to take? (max. 500 characters).', max_length=500, verbose_name='How do you plan to get there? Remember to highlight what makes your project design or idea different and innovative.'),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='collaboration_camp_option',
            field=models.CharField(choices=[('single_track', 'Single track'), ('partner_track', 'Partner track'), ('not_sure', "I'm not sure yet")], help_text='Choose one of the following options.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='challenge',
            field=models.TextField(help_text='max. 300 characters.', max_length=300, verbose_name='What problem or societal need are you working on?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='collaboration_camp_option',
            field=models.CharField(choices=[('single_track', 'Single track'), ('partner_track', 'Partner track'), ('not_sure', "I'm not sure yet")], help_text='Choose one of the following options.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea_sketch_archived', to='advocate_europe_ideas.Idea'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='outcome',
            field=models.TextField(help_text='If your project is selected, what will be different a year from now? What will have changed? (max. 300 characters).', max_length=300, verbose_name='What would be a successful outcome for your project?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='plan',
            field=models.TextField(help_text='Describe as concretely as possible the approach and / or the method you will use when implementing your idea. What are the steps you plan to take? (max. 500 characters).', max_length=500, verbose_name='How do you plan to get there? Remember to highlight what makes your project design or idea different and innovative.'),
        ),
    ]
