# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0004_rename_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='organisation_website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='organisation_website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_1_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_2_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_3_website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
    ]
