# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    def copy_jurystatement(apps, schema_editor):
        Proposal = apps.get_model('advocate_europe_ideas', 'proposal')
        for proposal in Proposal.objects.all():
            proposal.jury_statement = proposal.proposal_jury_statement
            proposal.save()


    dependencies = [
        ('advocate_europe_ideas', '0008_increase_orgnaisation_name_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='jury_statement',
            new_name='proposal_jury_statement',
        ),
        migrations.AddField(
            model_name='idea',
            name='jury_statement',
            field=models.TextField(blank=True, verbose_name='Why this idea?'),
        ),
        migrations.RunPython(copy_jurystatement),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_jury_statement',
        )
    ]
