# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0010_add_idea_follow_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='budget_granted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
