# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0011_idea_budget_granted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='collaborators',
            new_name='co_workers',
        ),
        migrations.RenameField(
            model_name='ideasketcharchived',
            old_name='collaborators',
            new_name='co_workers',
        ),
    ]
