# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0012_rename_collaborators_to_co_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='co_workers',
            field=models.ManyToManyField(blank=True, related_name='idea_co_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='co_workers',
            field=models.ManyToManyField(blank=True, related_name='ideasketcharchived_co_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
