# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 07:20
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0013_alter_field_co_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Please select one or two topics for your project.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Please select one or two topics for your project.', max_length=255),
        ),
    ]
