# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:40
from __future__ import unicode_literals

import adhocracy4.images.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0014_rename_idea_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Organisation email'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_image',
            field=adhocracy4.images.fields.ConfiguredImageField('idea_image', blank=True, help_text='Upload a photo or illustration that visually supports or explains your idea. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif of up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region'), ('online', 'Online'), ('ruhr_linkage', 'Linkage to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners, audiences, or in some other way? Please provide further details. (max. 200 characters)', max_length=200, verbose_name='Linkage to the Ruhr area'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location_specify',
            field=models.TextField(blank=True, help_text='Please specify the city, country and region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_pitch',
            field=models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and attractive text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_title',
            field=models.CharField(help_text='Give your idea a short and meaningful title. (max. 50 characters)', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and culture'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Please select 1-2 topics for your project. Your answer to this question does not influence the selection process. It helps us to get a better overview over the proposals we receive.', max_length=255, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_topics_other',
            field=models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250),
        ),
        migrations.AlterField(
            model_name='idea',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write here the name of your initiative or planned organisation.', max_length=300),
        ),
        migrations.AlterField(
            model_name='idea',
            name='organisation_status_extra',
            field=models.TextField(blank=True, help_text='Please provide details about your current status, especially if you selected "Other" (max. 200 characters)', max_length=200, verbose_name='Organisation details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_1_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_2_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partner_organisation_3_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='collaboration_camp_benefit',
            field=models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Collaboration Camp?'),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='collaboration_camp_option',
            field=models.CharField(choices=[('single_track', 'Single track'), ('partner_track', 'Partner track'), ('not_sure', 'I am not sure yet')], help_text='Choose one of the following options.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='collaboration_camp_represent',
            field=models.TextField(help_text='Specify one person only. (max 150 characters)', max_length=150, verbose_name='Who will represent your idea at the Collaboration Camp and why?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='collaboration_camp_benefit',
            field=models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Collaboration Camp?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='collaboration_camp_option',
            field=models.CharField(choices=[('single_track', 'Single track'), ('partner_track', 'Partner track'), ('not_sure', 'I am not sure yet')], help_text='Choose one of the following options.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='collaboration_camp_represent',
            field=models.TextField(help_text='Specify one person only. (max 150 characters)', max_length=150, verbose_name='Who will represent your idea at the Collaboration Camp and why?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Organisation email'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_image',
            field=adhocracy4.images.fields.ConfiguredImageField('idea_image', blank=True, help_text='Upload a photo or illustration that visually supports or explains your idea. Make sure that you have the property rights to share this picture. You can upload a .jpg, .png or .gif of up to 3 MB in size. The image should be in landscape (not portrait) format and have a width of at least 400 pixels.', upload_to='ideas/images', verbose_name='Visualise your idea'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region'), ('online', 'Online'), ('ruhr_linkage', 'Linkage to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners, audiences, or in some other way? Please provide further details. (max. 200 characters)', max_length=200, verbose_name='Linkage to the Ruhr area'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location_specify',
            field=models.TextField(blank=True, help_text='Please specify the city, country and region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_pitch',
            field=models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and attractive text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_title',
            field=models.CharField(help_text='Give your idea a short and meaningful title. (max. 50 characters)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and culture'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Please select 1-2 topics for your project. Your answer to this question does not influence the selection process. It helps us to get a better overview over the proposals we receive.', max_length=255, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_topics_other',
            field=models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write here the name of your initiative or planned organisation.', max_length=300),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='organisation_status_extra',
            field=models.TextField(blank=True, help_text='Please provide details about your current status, especially if you selected "Other" (max. 200 characters)', max_length=200, verbose_name='Organisation details'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_1_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_2_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partner_organisation_3_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Organisation Name'),
        ),
    ]
