# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:59
from __future__ import unicode_literals

from django.db import migrations


def add_creator_to_co_workers(apps, schema_editor):
    Idea = apps.get_model('advocate_europe_ideas', 'Idea')

    for idea in Idea.objects.all():
        if idea.creator not in idea.co_workers.all():
            idea.co_workers.add(idea.creator)


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0014_rename_idea_topic'),
    ]

    operations = [
        migrations.RunPython(add_creator_to_co_workers)
    ]
