# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0015_rename_several_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasketch',
            name='collaboration_camp_email',
        ),
        migrations.RemoveField(
            model_name='ideasketch',
            name='collaboration_camp_option',
        ),
        migrations.RemoveField(
            model_name='ideasketcharchived',
            name='collaboration_camp_email',
        ),
        migrations.RemoveField(
            model_name='ideasketcharchived',
            name='collaboration_camp_option',
        ),
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.TextField(help_text='How does your idea address the challenges of democracy in Europe today? How does it suit our 2017-2018 call for ideas with its question “What if we took the stage? Ideas for democracy in Europe.”? (max. 300 characters) ', max_length=300, verbose_name='How will your idea strengthen democracy in Europe?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='how_did_you_hear',
            field=models.CharField(choices=[('personal_contact', 'Personal contact'), ('websites', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('newsletter', 'Newsletter'), ('other', 'Other')], max_length=255, verbose_name='How did you hear about Advocate Europe?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region (please specify below)'), ('online', 'Online'), ('ruhr_linkage', 'Links to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences?', max_length=200, verbose_name='Links to the Ruhr area'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_location_specify',
            field=models.TextField(blank=True, help_text='Please specify the city, country and/or region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_pitch',
            field=models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and appealing text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Choose 1-2 topics that describe your project. Your answer to this question does not influence the selection process. It helps us to get a better overview of the proposals we receive.', max_length=255, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_topics_other',
            field=models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='members',
            field=models.TextField(help_text='Please introduce us to the main members of your project team and briefly summarise their experience and skills. (max. 500 characters)', max_length=500, verbose_name='Who is in your project team?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write the name of your initiative or planned  organisation here.', max_length=300),
        ),
        migrations.AlterField(
            model_name='idea',
            name='outcome',
            field=models.TextField(help_text='If your project is selected, what will be different a year from now? What will have changed? (max. 300 characters)', max_length=300, verbose_name='What would a successful outcome for your project be?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='partners_more_info',
            field=models.TextField(blank=True, help_text='Please use this field if you have more than 3 partner organisations or if you want to tell us more about your proposed partnership arrangements (max. 200 characters).', max_length=200, verbose_name='More information'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='plan',
            field=models.TextField(help_text='Describe as concretely as possible the approach and/or the method you will use when implementing your idea. What are the steps you plan to take? (max. 500 characters)', max_length=500, verbose_name='How do you plan to get there? Remember to highlight what makes your project design or idea different and innovative.'),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='collaboration_camp_represent',
            field=models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Collaboration Camp and why?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='challenge',
            field=models.TextField(help_text='How does your idea address the challenges of democracy in Europe today? How does it suit our 2017-2018 call for ideas with its question “What if we took the stage? Ideas for democracy in Europe.”? (max. 300 characters) ', max_length=300, verbose_name='How will your idea strengthen democracy in Europe?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='collaboration_camp_represent',
            field=models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Collaboration Camp and why?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='how_did_you_hear',
            field=models.CharField(choices=[('personal_contact', 'Personal contact'), ('websites', 'Website'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('newsletter', 'Newsletter'), ('other', 'Other')], max_length=255, verbose_name='How did you hear about Advocate Europe?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('city', 'City, country or region (please specify below)'), ('online', 'Online'), ('ruhr_linkage', 'Links to the Ruhr area of Germany')], help_text='Where will your idea take place? Choose all options that apply. 1-3 choices possible.', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences?', max_length=200, verbose_name='Links to the Ruhr area'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location_specify',
            field=models.TextField(blank=True, help_text='Please specify the city, country and/or region, e.g. Berlin, Germany. (max. 100 characters)', max_length=100, verbose_name='Location details'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_pitch',
            field=models.TextField(help_text='Present your idea in max. 500 characters. Share a concise and appealing text that makes the reader curious. Try to pitch your main challenge, objective, method and target group in 3-5 sentences.', max_length=500),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('democracy_participation', 'Democracy and participation'), ('arts_cultural_activities', 'Arts and cultural activities'), ('environment', 'Environment'), ('social_inclusion', 'Social inclusion'), ('migration', 'Migration'), ('communities', 'Communities'), ('urban_development', 'Urban development'), ('education', 'Education')], help_text='Choose 1-2 topics that describe your project. Your answer to this question does not influence the selection process. It helps us to get a better overview of the proposals we receive.', max_length=255, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_topics_other',
            field=models.CharField(blank=True, help_text='Please specify. (max 250 characters)', max_length=250, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='members',
            field=models.TextField(help_text='Please introduce us to the main members of your project team and briefly summarise their experience and skills. (max. 500 characters)', max_length=500, verbose_name='Who is in your project team?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='If you do not yet have a registered organisation, please write the name of your initiative or planned  organisation here.', max_length=300),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='outcome',
            field=models.TextField(help_text='If your project is selected, what will be different a year from now? What will have changed? (max. 300 characters)', max_length=300, verbose_name='What would a successful outcome for your project be?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='partners_more_info',
            field=models.TextField(blank=True, help_text='Please use this field if you have more than 3 partner organisations or if you want to tell us more about your proposed partnership arrangements (max. 200 characters).', max_length=200, verbose_name='More information'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='plan',
            field=models.TextField(help_text='Describe as concretely as possible the approach and/or the method you will use when implementing your idea. What are the steps you plan to take? (max. 500 characters)', max_length=500, verbose_name='How do you plan to get there? Remember to highlight what makes your project design or idea different and innovative.'),
        ),
    ]
