# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0016_rename_several_fields_and_delete_two_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences? Please provide further details. (max. 200 characters)', max_length=200, verbose_name='Links to the Ruhr area'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_location_ruhr',
            field=models.TextField(blank=True, help_text='Is your project connected to the Ruhr area of Germany through project partners or audiences? Please provide further details. (max. 200 characters)', max_length=200, verbose_name='Links to the Ruhr area'),
        ),
    ]
