# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0018_rename_collaboration_camp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasketch',
            name='idea_challenge_camp_benefit',
            field=models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Idea Challenge Camp?'),
        ),
        migrations.AlterField(
            model_name='ideasketch',
            name='idea_challenge_camp_represent',
            field=models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Idea Challenge Camp and why?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_challenge_camp_benefit',
            field=models.TextField(help_text='Tell us about your expectations. Think about your skills, resources, networks and partners when describing what you could offer and what you would like to take away. (max. 300 characters)', max_length=300, verbose_name='How could you contribute to and benefit from participating in the Idea Challenge Camp?'),
        ),
        migrations.AlterField(
            model_name='ideasketcharchived',
            name='idea_challenge_camp_represent',
            field=models.TextField(help_text='Specify one person only.', max_length=150, verbose_name='Who will represent your idea at the Idea Challenge Camp and why?'),
        ),
    ]
