# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 12:10
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.db import migrations, transaction


def copy_images(apps, schema_editor):
    IdeaSketchArchived = apps.get_model('advocate_europe_ideas', 'IdeaSketchArchived')
    for archive in IdeaSketchArchived.objects.all():
        idea = archive.idea
        if idea.idea_image:
            picture_copy = ContentFile(idea.idea_image.read())
            new_picture_name = 'archived_{}'.format(idea.idea_image.name.split("/")[-1])
            archive.idea_image.save(new_picture_name, picture_copy)
            picture_copy.close()


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_ideas', '0021_typo_and_longer_field'),
    ]

    operations = [
        migrations.RunPython(copy_images),
    ]
