# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('cms_settings', '0003_allow_blank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppages',
            name='selection_criteria',
            field=models.ForeignKey(blank=True, help_text='Please add a link to the page that explains the selection criteria here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_page_selection_criteria', to='wagtailcore.Page'),
        ),
    ]
