# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_settings', '0006_update_helptext_and_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationcampsettings',
            options={'verbose_name': 'Idea Challenge Camp Settings'},
        ),
    ]
