# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_images', '0002_copy_images'),
        ('cms_blog', '0002_auto_20170419_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='custom_image',
            field=models.ForeignKey(blank=True, help_text='The Image that is shown on the blog page and the blog index page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_images.CustomImage', verbose_name='Blog Image'),
        )
    ]
