# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0004_set_id_in_new_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='image',
        ),
    ]
