# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_blog', '0006_rename_new_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
