# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0005_remove_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='motto',
            new_name='biographie',
        ),
    ]
