# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0006_rename_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='europe',
            field=models.TextField(blank=True, help_text='Why do you care about Europe? Where do you try to make a change?(max. 250 characters)', verbose_name='Your interest in europe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biographie',
            field=models.TextField(blank=True, help_text='Tell us about yourself. fields of profession and interest.(max. 250 characters)', verbose_name='Short biographie'),
        ),
    ]
