# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:20
from __future__ import unicode_literals

import adhocracy4.images.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0007_add_europe_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biographie',
        ),
        migrations.AlterField(
            model_name='user',
            name='_avatar',
            field=adhocracy4.images.fields.ConfiguredImageField('avatar', blank=True, help_text='The image should be at least 340 pixel wide and 340 pixel high.', upload_to='users/images', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='europe',
            field=models.TextField(blank=True, help_text='Why do you care about Europe? Where do you try to make a change? (max. 200 characters)', max_length=200, verbose_name='Your interest in Europe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Plase add either https:// or http:// to the front of your URL.', verbose_name='Website'),
        ),
    ]
