# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0007_add_europe_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notifications',
            field=models.BooleanField(default=True, help_text='Designates whether you want to receive notifications. Unselect if you do not want to receive notifications.', verbose_name='Send me email notifications'),
        ),
    ]
