# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0008_rewording_and_more_helptexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notifications',
            field=models.BooleanField(default=True, help_text='Designates whether you want to receive notifications. Unselect if you do not want to receive notifications.', verbose_name='Send me email notifications'),
        ),
    ]
