# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:37
from __future__ import unicode_literals

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_users', '0010_change_notification_wording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_avatar',
            field=adhocracy4.images.fields.ConfiguredImageField('avatar', blank=True, help_text='Please upload a squared image, at least 340x340 px. Allowed formats are jpg, gif and png.', upload_to='users/images', verbose_name='Profile picture'),
        ),
    ]
