# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0007_add_blog_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
