# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:53
from __future__ import unicode_literals

from django.db import migrations


def set_custom_image_id(apps, schema_editor):
    CustomImage = apps.get_model('cms_images', 'CustomImage')
    HomePage = apps.get_model('cms_home', 'HomePage')

    for hp in HomePage.objects.all():
        if hp.image:
            image = hp.image
            hp.custom_image_id = CustomImage.objects.get(id=image.id)
            hp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0009_homepage_custom_image'),
    ]

    operations = [
        migrations.RunPython(set_custom_image_id)
    ]
