# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0010_set_id_in_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='custom_image',
            field=models.ForeignKey(blank=True, help_text='The Image that is shown on top of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_images.CustomImage', verbose_name='Header Image'),
        ),
    ]
