# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0017_update_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='image_1',
        ),
    ]
