# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_home', '0019_add_additional_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_button_text_de',
            field=models.CharField(default='Video abspielen', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_button_text_en',
            field=models.CharField(default='Play Video', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='website_link_text_de',
            field=models.CharField(default='mehr', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='website_link_text_en',
            field=models.CharField(default='more', max_length=100),
        ),
    ]
