# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_snippets', '0004_remove_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name',
        ),
    ]
