# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_snippets', '0005_rename_english_category_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_de',
        ),
    ]
