# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_snippets', '0006_remove_category_name_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='menuitem_ptr',
        ),
        migrations.RemoveField(
            model_name='navigationmenuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='NavigationMenu',
        ),
        migrations.DeleteModel(
            name='NavigationMenuItem',
        ),
    ]
