# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_journeys', '0002_journeyentry_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyentry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
