# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_journeys', '0005_add_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyentry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='To add content from Vimeo, Youtube, Facebook, flickr, soundcloud or instagram just paste the url into the text.'),
        ),
    ]
