# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_europe_journeys', '0006_update_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyentry',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
